/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice_java;
import java.util.Scanner;
import java.util.ArrayList;
import problems.*;


public class App {
    public String getGreeting() {
        return "Welcome, Please Enter problem number";
    }
    public static void main(String[] args) {
		System.out.println(new App().getGreeting());
		listProblems();
		Scanner sc = new Scanner(System.in);
		int p_num = sc.nextInt();
		run_problems(p_num);
    }

	public static void run_problems(int p_num){
		Problem p = null;
		switch(p_num){
			case 2562:
				p = new Problem_2562();
				break;
			case 10818:
				p = new Problem_10818();
				break;
			default:
				break;
		}
		if (p!=null){
			System.out.println(p.getDescription());
			p.run();
		}else
			System.out.println("There is no problem number "
					+"matching you entered. "
					+"Try Again.");
	}

	public static void listProblems(){
		ArrayList<Integer> arr = new ArrayList<>();
		arr.add(10818);
		arr.add(2562);	
		System.out.println("Here is Problems we got: ");
		for(int i : arr){
			System.out.print(i+" ");
		}
		System.out.println();
	}
}
